export interface Timezones{
  OFFSET?: number;
  ID: string;
  GMT_TIME_STAMP?: string;
  DISPLAY_NAME?:string;
}
export const timezones = [
  {
    OFFSET: -43200000,
    ID: 'Etc/GMT+12',
    GMT_TIME_STAMP: '-12:00',
    DISPLAY_NAME: 'GMT-12:00',
  },
  {
    OFFSET: -39600000,
    SUB_GROUP: ['Pacific/Pago_Pago', 'Pacific/Midway'],
    ID: 'US/Samoa',
    GMT_TIME_STAMP: '-11:00',
    DISPLAY_NAME: 'Samoa Standard Time',
  },
  {
    OFFSET: -39600000,
    ID: 'Pacific/Niue',
    GMT_TIME_STAMP: '-11:00',
    DISPLAY_NAME: 'Niue Time',
  },
  {
    OFFSET: -36000000,
    SUB_GROUP: ['Pacific/Johnston', 'US/Hawaii'],
    ID: 'Pacific/Honolulu',
    GMT_TIME_STAMP: '-10:00',
    DISPLAY_NAME: 'Hawaii Standard Time',
  },
  {
    OFFSET: -36000000,
    ID: 'Pacific/Rarotonga',
    GMT_TIME_STAMP: '-10:00',
    DISPLAY_NAME: 'Cook Is. Time',
  },
  {
    OFFSET: -36000000,
    ID: 'Pacific/Tahiti',
    GMT_TIME_STAMP: '-10:00',
    DISPLAY_NAME: 'Tahiti Time',
  },
  {
    OFFSET: -34200000,
    ID: 'Pacific/Marquesas',
    GMT_TIME_STAMP: '-9:30',
    DISPLAY_NAME: 'Marquesas Time',
  },
  {
    OFFSET: -32400000,
    SUB_GROUP: ['America/Adak', 'America/Atka'],
    ID: 'US/Aleutian',
    GMT_TIME_STAMP: '-9:00',
    DISPLAY_NAME: 'Hawaii Daylight Time',
  },
  {
    OFFSET: -32400000,
    ID: 'Pacific/Gambier',
    GMT_TIME_STAMP: '-9:00',
    DISPLAY_NAME: 'Gambier Time',
  },
  {
    OFFSET: -28800000,
    SUB_GROUP: [
      'America/Juneau',
      'America/Nome',
      'America/Sitka',
      'America/Yakutat',
      'US/Alaska',
    ],
    ID: 'America/Anchorage',
    GMT_TIME_STAMP: '-8:00',
    DISPLAY_NAME: 'Alaska Daylight Time',
  },
  {
    OFFSET: -28800000,
    ID: 'America/Metlakatla',
    GMT_TIME_STAMP: '-8:00',
    DISPLAY_NAME: 'Alaska Daylight Time',
  },
  {
    OFFSET: -28800000,
    ID: 'Pacific/Pitcairn',
    GMT_TIME_STAMP: '-8:00',
    DISPLAY_NAME: 'Pitcairn Standard Time',
  },
  {
    OFFSET: -25200000,
    SUB_GROUP: [
      'America/Dawson_Creek',
      'America/Fort_Nelson',
      'America/Hermosillo',
      'America/Phoenix',
      'US/Arizona',
    ],
    ID: 'America/Creston',
    GMT_TIME_STAMP: '-7:00',
    DISPLAY_NAME: 'Mountain Standard Time',
  },
  {
    OFFSET: -25200000,
    SUB_GROUP: [
      'America/Dawson',
      'America/Ensenada',
      'America/Los_Angeles',
      'America/Vancouver',
      'America/Whitehorse',
      'Canada/Pacific',
      'Canada/Yukon',
      'Mexico/BajaNorte',
      'US/Pacific',
      'US/Pacific-New',
    ],
    ID: 'America/Tijuana',
    GMT_TIME_STAMP: '-7:00',
    DISPLAY_NAME: 'Pacific Daylight Time',
  },
  {
    OFFSET: -25200000,
    ID: 'America/Santa_Isabel',
    GMT_TIME_STAMP: '-7:00',
    DISPLAY_NAME: 'Pacific Daylight Time',
  },
  {
    OFFSET: -21600000,
    SUB_GROUP: [
      'America/Costa_Rica',
      'America/El_Salvador',
      'America/Guatemala',
      'America/Managua',
      'America/Regina',
      'America/Swift_Current',
      'America/Tegucigalpa',
      'Canada/Saskatchewan',
    ],
    ID: 'America/Belize',
    GMT_TIME_STAMP: '-6:00',
    DISPLAY_NAME: 'Central Standard Time',
  },
  {
    OFFSET: -21600000,
    SUB_GROUP: [
      'America/Boise',
      'America/Cambridge_Bay',
      'America/Edmonton',
      'America/Inuvik',
      'America/Ojinaga',
      'America/Shiprock',
      'America/Yellowknife',
      'Canada/Mountain',
      'Navajo',
      'US/Mountain',
    ],
    ID: 'America/Denver',
    GMT_TIME_STAMP: '-6:00',
    DISPLAY_NAME: 'Mountain Daylight Time',
  },
  {
    OFFSET: -21600000,
    SUB_GROUP: ['America/Mazatlan', 'Mexico/BajaSur'],
    ID: 'America/Chihuahua',
    GMT_TIME_STAMP: '-6:00',
    DISPLAY_NAME: 'Mountain Daylight Time',
  },
  {
    OFFSET: -21600000,
    ID: 'Chile/EasterIsland',
    GMT_TIME_STAMP: '-6:00',
    DISPLAY_NAME: 'Easter Is. Time',
  },
  {
    OFFSET: -21600000,
    ID: 'Pacific/Galapagos',
    GMT_TIME_STAMP: '-6:00',
    DISPLAY_NAME: 'Galapagos Time',
  },
  {
    OFFSET: -18000000,
    SUB_GROUP: ['America/Rio_Branco', 'America/Eirunepe'],
    ID: 'Brazil/Acre',
    GMT_TIME_STAMP: '-5:00',
    DISPLAY_NAME: 'Acre Time',
  },
  {
    OFFSET: -18000000,
    SUB_GROUP: [
      'America/Atikokan',
      'America/Cancun',
      'America/Coral_Harbour',
      'America/Panama',
    ],
    ID: 'America/Jamaica',
    GMT_TIME_STAMP: '-5:00',
    DISPLAY_NAME: 'Eastern Standard Time',
  },
  {
    OFFSET: -18000000,
    SUB_GROUP: [
      'America/Indiana/Knox',
      'America/Indiana/Tell_City',
      'America/Matamoros',
      'America/Menominee',
      'America/North_Dakota/Beulah',
      'America/North_Dakota/Center',
      'America/North_Dakota/New_Salem',
      'America/Rainy_River',
      'America/Rankin_Inlet',
      'America/Resolute',
      'America/Winnipeg',
      'Canada/Central',
      'US/Central',
      'US/Indiana-Starke',
    ],
    ID: 'America/Chicago',
    GMT_TIME_STAMP: '-5:00',
    DISPLAY_NAME: 'Central Daylight Time',
  },
  {
    OFFSET: -18000000,
    SUB_GROUP: [
      'America/Bahia_Banderas',
      'America/Merida',
      'America/Monterrey',
    ],
    ID: 'America/Mexico_City',
    GMT_TIME_STAMP: '-5:00',
    DISPLAY_NAME: 'Central Daylight Time',
  },
  {
    OFFSET: -18000000,
    ID: 'America/Bogota',
    GMT_TIME_STAMP: '-5:00',
    DISPLAY_NAME: 'Colombia Time',
  },
  {
    OFFSET: -18000000,
    ID: 'America/Guayaquil',
    GMT_TIME_STAMP: '-5:00',
    DISPLAY_NAME: 'Ecuador Time',
  },
  {
    OFFSET: -18000000,
    ID: 'America/Lima',
    GMT_TIME_STAMP: '-5:00',
    DISPLAY_NAME: 'Peru Time',
  },
  {
    OFFSET: -14400000,
    SUB_GROUP: ['Antarctica/Palmer', 'Chile/Continental'],
    ID: 'America/Santiago',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Chile Time',
  },
  {
    OFFSET: -14400000,
    SUB_GROUP: ['America/Manaus', 'America/Porto_Velho', 'Brazil/West'],
    ID: 'America/Boa_Vista',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Amazon Time',
  },
  {
    OFFSET: -14400000,
    SUB_GROUP: [
      'America/Anguilla',
      'America/Antigua',
      'America/Aruba',
      'America/Barbados',
      'America/Blanc-Sablon',
      'America/Curacao',
      'America/Dominica',
      'America/Grand_Turk',
      'America/Grenada',
      'America/Guadeloupe',
      'America/Kralendijk',
      'America/Lower_Princes',
      'America/Martinique',
      'America/Montserrat',
      'America/Port_of_Spain',
      'America/Puerto_Rico',
      'America/Santo_Domingo',
      'America/St_Barthelemy',
      'America/St_Kitts',
      'America/St_Lucia',
      'America/St_Thomas',
      'America/St_Vincent',
      'America/Tortola',
      'America/Virgin',
    ],
    ID: 'America/Marigot',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Atlantic Standard Time',
  },
  {
    OFFSET: -14400000,
    SUB_GROUP: ['America/Cuiaba'],
    ID: 'America/Campo_Grande',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Amazon Time',
  },
  {
    OFFSET: -14400000,
    SUB_GROUP: ['America/Havana'],
    ID: 'Cuba',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Cuba Daylight Time',
  },
  {
    OFFSET: -14400000,
    SUB_GROUP: [
      'America/Detroit',
      'America/Cayman',
      'America/Fort_Wayne',
      'America/Indiana/Marengo',
      'America/Indiana/Petersburg',
      'America/Indiana/Vevay',
      'America/Indiana/Vincennes',
      'America/Indiana/Winamac',
      'America/Indianapolis',
      'America/Iqaluit',
      'America/Kentucky/Monticello',
      'America/Louisville',
      'America/Montreal',
      'America/Nassau',
      'America/Nipigon',
      'America/Pangnirtung',
      'America/Port-au-Prince',
      'America/Thunder_Bay',
      'America/Toronto',
      'Canada/Eastern',
      'US/East-Indiana',
      'US/Eastern',
      'US/Michigan',
    ],
    ID: 'America/New_York',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Eastern Daylight Time',
  },
  {
    OFFSET: -14400000,
    ID: 'America/Asuncion',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Paraguay Time',
  },
  {
    OFFSET: -14400000,
    ID: 'America/Caracas',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Venezuela Time',
  },
  {
    OFFSET: -14400000,
    ID: 'America/Guyana',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Guyana Time',
  },
  {
    OFFSET: -14400000,
    ID: 'America/La_Paz',
    GMT_TIME_STAMP: '-4:00',
    DISPLAY_NAME: 'Bolivia Time',
  },
  {
    OFFSET: -10800000,
    SUB_GROUP: [
      'America/Argentina/ComodRivadavia',
      'America/Argentina/La_Rioja',
      'America/Argentina/Rio_Gallegos',
      'America/Argentina/Salta',
      'America/Argentina/San_Juan',
      'America/Argentina/San_Luis',
      'America/Argentina/Tucuman',
      'America/Argentina/Ushuaia',
      'America/Buenos_Aires',
      'America/Catamarca',
      'America/Jujuy',
      'America/Mendoza',
      'America/Rosario',
    ],
    ID: 'America/Cordoba',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Argentine Time',
  },
  {
    OFFSET: -10800000,
    SUB_GROUP: [
      'America/Bahia',
      'America/Belem',
      'America/Fortaleza',
      'America/Maceio',
      'America/Recife',
      'America/Santarem',
    ],
    ID: 'America/Araguaina',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Brasilia Time',
  },
  {
    OFFSET: -10800000,
    SUB_GROUP: [
      'America/Goose_Bay',
      'America/Halifax',
      'America/Moncton',
      'America/Thule',
      'Atlantic/Bermuda',
      'Canada/Atlantic',
    ],
    ID: 'America/Glace_Bay',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Atlantic Daylight Time',
  },
  {
    OFFSET: -10800000,
    SUB_GROUP: ['America/Sao_Paulo'],
    ID: 'Brazil/East',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Brasilia Time',
  },
  {
    OFFSET: -10800000,
    ID: 'America/Cayenne',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'French Guiana Time',
  },
  {
    OFFSET: -10800000,
    ID: 'America/Montevideo',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Uruguay Time',
  },
  {
    OFFSET: -10800000,
    ID: 'America/Paramaribo',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Suriname Time',
  },
  {
    OFFSET: -10800000,
    ID: 'America/Punta_Arenas',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'GMT-03:00',
  },
  {
    OFFSET: -10800000,
    ID: 'Antarctica/Rothera',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Rothera Time',
  },
  {
    OFFSET: -10800000,
    ID: 'Atlantic/Stanley',
    GMT_TIME_STAMP: '-3:00',
    DISPLAY_NAME: 'Falkland Is. Time',
  },
  {
    OFFSET: -9000000,
    SUB_GROUP: ['America/St_Johns'],
    ID: 'Canada/Newfoundland',
    GMT_TIME_STAMP: '-2:30',
    DISPLAY_NAME: 'Newfoundland Daylight Time',
  },
  {
    OFFSET: -7200000,
    SUB_GROUP: ['Brazil/DeNoronha'],
    ID: 'America/Noronha',
    GMT_TIME_STAMP: '-2:00',
    DISPLAY_NAME: 'Fernando de Noronha Time',
  },
  {
    OFFSET: -7200000,
    ID: 'America/Godthab',
    GMT_TIME_STAMP: '-2:00',
    DISPLAY_NAME: 'Western Greenland Summer Time',
  },
  {
    OFFSET: -7200000,
    ID: 'America/Miquelon',
    GMT_TIME_STAMP: '-2:00',
    DISPLAY_NAME: 'Pierre & Miquelon Daylight Time',
  },
  {
    OFFSET: -7200000,
    ID: 'America/Nuuk',
    GMT_TIME_STAMP: '-2:00',
    DISPLAY_NAME: 'Western Greenland Summer Time',
  },
  {
    OFFSET: -7200000,
    ID: 'Atlantic/South_Georgia',
    GMT_TIME_STAMP: '-2:00',
    DISPLAY_NAME: 'South Georgia Standard Time',
  },
  {
    OFFSET: -3600000,
    ID: 'Atlantic/Cape_Verde',
    GMT_TIME_STAMP: '-1:00',
    DISPLAY_NAME: 'Cape Verde Time',
  },
  {
    OFFSET: 0,
    SUB_GROUP: ['Zulu', 'Antarctica/Troll'],
    ID: 'Universal',
    GMT_TIME_STAMP: '0:00',
    DISPLAY_NAME: 'Coordinated Universal Time',
  },
  {
    OFFSET: 0,
    SUB_GROUP: [
      'Africa/Abidjan',
      'Africa/Bamako',
      'Africa/Banjul',
      'Africa/Bissau',
      'Africa/Conakry',
      'Africa/Dakar',
      'Africa/Freetown',
      'Africa/Lome',
      'Africa/Monrovia',
      'Africa/Nouakchott',
      'Africa/Ouagadougou',
      'Africa/Sao_Tome',
      'Africa/Timbuktu',
      'Atlantic/Reykjavik',
      'Atlantic/St_Helena',
      'Iceland',
    ],
    ID: 'America/Danmarkshavn',
    GMT_TIME_STAMP: '0:00',
    DISPLAY_NAME: 'Greenwich Mean Time',
  },
  {
    OFFSET: 0,
    SUB_GROUP: ['Africa/El_Aaiun'],
    ID: 'Africa/Casablanca',
    GMT_TIME_STAMP: '0:00',
    DISPLAY_NAME: 'Western European Summer Time',
  },
  {
    OFFSET: 0,
    ID: 'Africa/Accra',
    GMT_TIME_STAMP: '0:00',
    DISPLAY_NAME: 'Ghana Mean Time',
  },
  {
    OFFSET: 0,
    ID: 'America/Scoresbysund',
    GMT_TIME_STAMP: '0:00',
    DISPLAY_NAME: 'Eastern Greenland Summer Time',
  },
  {
    OFFSET: 0,
    ID: 'Atlantic/Azores',
    GMT_TIME_STAMP: '0:00',
    DISPLAY_NAME: 'Azores Summer Time',
  },
  {
    OFFSET: 3600000,
    SUB_GROUP: ['Africa/Tunis'],
    ID: 'Africa/Algiers',
    GMT_TIME_STAMP: '+1:00',
    DISPLAY_NAME: 'Central European Time',
  },
  {
    OFFSET: 3600000,
    SUB_GROUP: [
      'Africa/Brazzaville',
      'Africa/Douala',
      'Africa/Kinshasa',
      'Africa/Lagos',
      'Africa/Libreville',
      'Africa/Luanda',
      'Africa/Malabo',
      'Africa/Ndjamena',
      'Africa/Niamey',
      'Africa/Porto-Novo',
    ],
    ID: 'Africa/Bangui',
    GMT_TIME_STAMP: '+1:00',
    DISPLAY_NAME: 'Western African Time',
  },
  {
    OFFSET: 3600000,
    SUB_GROUP: [
      'Europe/Belfast',
      'Europe/Guernsey',
      'Europe/Isle_of_Man',
      'Europe/Jersey',
    ],
    ID: 'Europe/London',
    GMT_TIME_STAMP: '+1:00',
    DISPLAY_NAME: 'British Summer Time',
  },
  {
    OFFSET: 3600000,
    SUB_GROUP: ['Eire'],
    ID: 'Europe/Dublin',
    GMT_TIME_STAMP: '+1:00',
    DISPLAY_NAME: 'Irish Summer Time',
  },
  {
    OFFSET: 3600000,
    SUB_GROUP: [
      'Atlantic/Faeroe',
      'Atlantic/Madeira',
      'Europe/Lisbon',
      'Atlantic/Canary',
    ],
    ID: 'Portugal',
    GMT_TIME_STAMP: '+1:00',
    DISPLAY_NAME: 'Western European Summer Time',
  },
  {
    OFFSET: 3600000,
    ID: 'Atlantic/Faroe',
    GMT_TIME_STAMP: '+1:00',
    DISPLAY_NAME: 'Western European Summer Time',
  },
  {
    OFFSET: 7200000,
    SUB_GROUP: [
      'Africa/Bujumbura',
      'Africa/Gaborone',
      'Africa/Harare',
      'Africa/Kigali',
      'Africa/Lubumbashi',
      'Africa/Lusaka',
      'Africa/Maputo',
    ],
    ID: 'Africa/Blantyre',
    GMT_TIME_STAMP: '+2:00',
    DISPLAY_NAME: 'Central African Time',
  },
  {
    OFFSET: 7200000,
    SUB_GROUP: [
      'Africa/Cairo',
      'Africa/Tripoli',
      'Europe/Kaliningrad',
      'Libya',
    ],
    ID: 'Egypt',
    GMT_TIME_STAMP: '+2:00',
    DISPLAY_NAME: 'Eastern European Time',
  },
  {
    OFFSET: 7200000,
    SUB_GROUP: ['Africa/Johannesburg', 'Africa/Mbabane'],
    ID: 'Africa/Maseru',
    GMT_TIME_STAMP: '+2:00',
    DISPLAY_NAME: 'South Africa Standard Time',
  },
  {
    OFFSET: 7200000,
    SUB_GROUP: [
      'Antarctica/Troll',
      'Arctic/Longyearbyen',
      'Atlantic/Jan_Mayen',
      'Africa/Ceuta',
      'Europe/Andorra',
      'Europe/Belgrade',
      'Europe/Berlin',
      'Europe/Bratislava',
      'Europe/Brussels',
      'Europe/Budapest',
      'Europe/Busingen',
      'Europe/Copenhagen',
      'Europe/Gibraltar',
      'Europe/Ljubljana',
      'Europe/Luxembourg',
      'Europe/Madrid',
      'Europe/Malta',
      'Europe/Monaco',
      'Europe/Oslo',
      'Europe/Paris',
      'Europe/Podgorica',
      'Europe/Prague',
      'Europe/Rome',
      'Europe/San_Marino',
      'Europe/Sarajevo',
      'Europe/Skopje',
      'Europe/Stockholm',
      'Europe/Tirane',
      'Europe/Vaduz',
      'Europe/Vatican',
      'Europe/Vienna',
      'Europe/Warsaw',
      'Europe/Zagreb',
      'Europe/Zurich',
      'Poland',
    ],
    ID: 'Europe/Amsterdam',
    GMT_TIME_STAMP: '+2:00',
    DISPLAY_NAME: 'Central European Summer Time',
  },
  {
    OFFSET: 7200000,
    ID: 'Africa/Windhoek',
    GMT_TIME_STAMP: '+2:00',
    DISPLAY_NAME: 'Central African Time',
  },
  {
    OFFSET: 7200000,
    ID: 'MET',
    GMT_TIME_STAMP: '+2:00',
    DISPLAY_NAME: 'Middle Europe Summer Time',
  },
  {
    OFFSET: 10800000,
    SUB_GROUP: [
      'Asia/Aden',
      'Asia/Baghdad',
      'Asia/Bahrain',
      'Asia/Qatar',
      'Asia/Riyadh',
    ],
    ID: 'Asia/Kuwait',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'Arabia Standard Time',
  },
  {
    OFFSET: 10800000,
    SUB_GROUP: [
      'Africa/Addis_Ababa',
      'Africa/Asmara',
      'Africa/Dar_es_Salaam',
      'Africa/Djibouti',
      'Africa/Juba',
      'Africa/Khartoum',
      'Africa/Mogadishu',
      'Africa/Nairobi',
      'Indian/Antananarivo',
      'Indian/Comoro',
      'Indian/Mayotte',
    ],
    ID: 'Africa/Kampala',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'Eastern African Time',
  },
  {
    OFFSET: 10800000,
    SUB_GROUP: ['Europe/Simferopol', 'Europe/Volgograd'],
    ID: 'Europe/Moscow',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'Moscow Standard Time',
  },
  {
    OFFSET: 10800000,
    SUB_GROUP: [
      'Asia/Amman',
      'Asia/Beirut',
      'Asia/Damascus',
      'Asia/Gaza',
      'Asia/Hebron',
      'Asia/Istanbul',
      'Asia/Nicosia',
      'Europe/Athens',
      'Europe/Bucharest',
      'Europe/Chisinau',
      'Europe/Helsinki',
      'Europe/Istanbul',
      'Europe/Kiev',
      'Europe/Mariehamn',
      'Europe/Nicosia',
      'Europe/Riga',
      'Europe/Sofia',
      'Europe/Tallinn',
      'Europe/Tiraspol',
      'Europe/Uzhgorod',
      'Europe/Vilnius',
      'Europe/Zaporozhye',
    ],
    ID: 'Turkey',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'Turkey Time',
  },
  {
    OFFSET: 10800000,
    SUB_GROUP: ['Asia/Jerusalem', 'Asia/Tel_Aviv'],
    ID: 'Israel',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'Israel Daylight Time',
  },
  {
    OFFSET: 10800000,
    ID: 'Antarctica/Syowa',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'Syowa Time',
  },
  {
    OFFSET: 10800000,
    ID: 'Asia/Famagusta',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'GMT+03:00',
  },
  {
    OFFSET: 10800000,
    ID: 'Europe/Kirov',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'GMT+03:00',
  },
  {
    OFFSET: 10800000,
    ID: 'Europe/Minsk',
    GMT_TIME_STAMP: '+3:00',
    DISPLAY_NAME: 'Moscow Standard Time',
  },
  {
    OFFSET: 14400000,
    SUB_GROUP: ['Asia/Muscat'],
    ID: 'Asia/Dubai',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Gulf Standard Time',
  },
  {
    OFFSET: 14400000,
    ID: 'Asia/Baku',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Azerbaijan Time',
  },
  {
    OFFSET: 14400000,
    ID: 'Asia/Tbilisi',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Georgia Time',
  },
  {
    OFFSET: 14400000,
    ID: 'Asia/Yerevan',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Armenia Time',
  },
  {
    OFFSET: 14400000,
    ID: 'Europe/Astrakhan',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'GMT+04:00',
  },
  {
    OFFSET: 14400000,
    ID: 'Europe/Samara',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Samara Time',
  },
  {
    OFFSET: 14400000,
    ID: 'Europe/Saratov',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'GMT+04:00',
  },
  {
    OFFSET: 14400000,
    ID: 'Europe/Ulyanovsk',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'GMT+04:00',
  },
  {
    OFFSET: 14400000,
    ID: 'Indian/Mahe',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Seychelles Time',
  },
  {
    OFFSET: 14400000,
    ID: 'Indian/Mauritius',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Mauritius Time',
  },
  {
    OFFSET: 14400000,
    ID: 'Indian/Reunion',
    GMT_TIME_STAMP: '+4:00',
    DISPLAY_NAME: 'Reunion Time',
  },
  {
    OFFSET: 16200000,
    SUB_GROUP: ['Asia/Tehran'],
    ID: 'Iran',
    GMT_TIME_STAMP: '+4:30',
    DISPLAY_NAME: 'Iran Daylight Time',
  },
  {
    OFFSET: 16200000,
    ID: 'Asia/Kabul',
    GMT_TIME_STAMP: '+4:30',
    DISPLAY_NAME: 'Afghanistan Time',
  },
  {
    OFFSET: 18000000,
    SUB_GROUP: ['Asia/Tashkent'],
    ID: 'Asia/Samarkand',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Uzbekistan Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Antarctica/Mawson',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Mawson Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Aqtau',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Aqtau Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Aqtobe',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Aqtobe Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Ashkhabad',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Turkmenistan Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Atyrau',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'GMT+05:00',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Dushanbe',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Tajikistan Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Karachi',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Pakistan Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Oral',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Oral Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Qyzylorda',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Qyzylorda Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Asia/Yekaterinburg',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Yekaterinburg Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Indian/Kerguelen',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'French Southern & Antarctic Lands Time',
  },
  {
    OFFSET: 18000000,
    ID: 'Indian/Maldives',
    GMT_TIME_STAMP: '+5:00',
    DISPLAY_NAME: 'Maldives Time',
  },
  {
    OFFSET: 19800000,
    SUB_GROUP: ['Asia/Colombo'],
    ID: 'Asia/Kolkata',
    GMT_TIME_STAMP: '+5:30',
    DISPLAY_NAME: 'India Standard Time',
  },
  {
    OFFSET: 20700000,
    ID: 'Asia/Kathmandu',
    GMT_TIME_STAMP: '+5:45',
    DISPLAY_NAME: 'Nepal Time',
  },
  {
    OFFSET: 21600000,
    SUB_GROUP: ['Asia/Urumqi'],
    ID: 'Asia/Kashgar',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Xinjiang Standard Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Antarctica/Vostok',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Vostok Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Asia/Almaty',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Alma-Ata Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Asia/Bishkek',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Kirgizstan Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Asia/Dhaka',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Bangladesh Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Asia/Omsk',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Omsk Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Asia/Qostanay',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Kostanay Standard Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Asia/Thimphu',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Bhutan Time',
  },
  {
    OFFSET: 21600000,
    ID: 'Indian/Chagos',
    GMT_TIME_STAMP: '+6:00',
    DISPLAY_NAME: 'Indian Ocean Territory Time',
  },
  {
    OFFSET: 23400000,
    ID: 'Asia/Rangoon',
    GMT_TIME_STAMP: '+6:30',
    DISPLAY_NAME: 'Myanmar Time',
  },
  {
    OFFSET: 23400000,
    ID: 'Asia/Yangon',
    GMT_TIME_STAMP: '+6:30',
    DISPLAY_NAME: 'Myanmar Time',
  },
  {
    OFFSET: 23400000,
    ID: 'Indian/Cocos',
    GMT_TIME_STAMP: '+6:30',
    DISPLAY_NAME: 'Cocos Islands Time',
  },
  {
    OFFSET: 25200000,
    SUB_GROUP: [
      'Asia/Ho_Chi_Minh',
      'Asia/Phnom_Penh',
      'Asia/Saigon',
      'Asia/Vientiane',
    ],
    ID: 'Asia/Bangkok',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'Indochina Time',
  },
  {
    OFFSET: 25200000,
    SUB_GROUP: ['Asia/Novokuznetsk'],
    ID: 'Asia/Krasnoyarsk',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'Krasnoyarsk Time',
  },
  {
    OFFSET: 25200000,
    SUB_GROUP: ['Asia/Pontianak'],
    ID: 'Asia/Jakarta',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'West Indonesia Time',
  },
  {
    OFFSET: 25200000,
    ID: 'Antarctica/Davis',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'Davis Time',
  },
  {
    OFFSET: 25200000,
    ID: 'Asia/Barnaul',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'GMT+07:00',
  },
  {
    OFFSET: 25200000,
    ID: 'Asia/Hovd',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'Hovd Time',
  },
  {
    OFFSET: 25200000,
    ID: 'Asia/Novosibirsk',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'Novosibirsk Time',
  },
  {
    OFFSET: 25200000,
    ID: 'Asia/Tomsk',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'GMT+07:00',
  },
  {
    OFFSET: 25200000,
    ID: 'Indian/Christmas',
    GMT_TIME_STAMP: '+7:00',
    DISPLAY_NAME: 'Christmas Island Time',
  },
  {
    OFFSET: 28800000,
    SUB_GROUP: ['Antarctica/Casey', 'Australia/West'],
    ID: 'Australia/Perth',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Australian Western Standard Time',
  },
  {
    OFFSET: 28800000,
    SUB_GROUP: ['Asia/Ujung_Pandang'],
    ID: 'Asia/Makassar',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Central Indonesia Time',
  },
  {
    OFFSET: 28800000,
    SUB_GROUP: ['Asia/Chongqing', 'Asia/Harbin', 'Asia/Taipei'],
    ID: 'Asia/Shanghai',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'China Standard Time',
  },
  {
    OFFSET: 28800000,
    SUB_GROUP: ['Asia/Kuching'],
    ID: 'Asia/Kuala_Lumpur',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Malaysia Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Brunei',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Brunei Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Choibalsan',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Choibalsan Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Hong_Kong',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Hong Kong Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Macao',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'China Standard Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Macau',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'China Standard Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Manila',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Philippines Standard Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Singapore',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Singapore Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Asia/Ulaanbaatar',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Ulaanbaatar Time',
  },
  {
    OFFSET: 28800000,
    ID: 'Hongkong',
    GMT_TIME_STAMP: '+8:00',
    DISPLAY_NAME: 'Hong Kong Time',
  },
  {
    OFFSET: 31500000,
    ID: 'Australia/Eucla',
    GMT_TIME_STAMP: '+8:45',
    DISPLAY_NAME: 'Australian Central Western Standard Time',
  },
  {
    OFFSET: 32400000,
    SUB_GROUP: ['Asia/Irkutsk'],
    ID: 'Asia/Chita',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Yakutsk Time',
  },
  {
    OFFSET: 32400000,
    SUB_GROUP: ['Japan'],
    ID: 'Asia/Tokyo',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Japan Standard Time',
  },
  {
    OFFSET: 32400000,
    ID: 'Asia/Dili',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Timor-Leste Time',
  },
  {
    OFFSET: 32400000,
    ID: 'Asia/Jayapura',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'East Indonesia Time',
  },
  {
    OFFSET: 32400000,
    ID: 'Asia/Khandyga',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Yakutsk Time',
  },
  {
    OFFSET: 32400000,
    ID: 'Asia/Pyongyang',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Korea Standard Time',
  },
  {
    OFFSET: 32400000,
    ID: 'Asia/Seoul',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Korea Standard Time',
  },
  {
    OFFSET: 32400000,
    ID: 'Asia/Yakutsk',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Yakutsk Time',
  },
  {
    OFFSET: 32400000,
    ID: 'Pacific/Palau',
    GMT_TIME_STAMP: '+9:00',
    DISPLAY_NAME: 'Palau Time',
  },
  {
    OFFSET: 34200000,
    SUB_GROUP: ['Australia/North'],
    ID: 'Australia/Darwin',
    GMT_TIME_STAMP: '+9:30',
    DISPLAY_NAME: 'Australian Central Standard Time (Northern Territory)',
  },
  {
    OFFSET: 34200000,
    SUB_GROUP: [
      'Australia/Adelaide',
      'Australia/Broken_Hill',
      'Australia/Yancowinna',
    ],
    ID: 'Australia/South',
    GMT_TIME_STAMP: '+9:30',
    DISPLAY_NAME: 'Australian Central Standard Time (South Australia)',
  },
  {
    OFFSET: 36000000,
    SUB_GROUP: ['Australia/Queensland', 'Australia/Lindeman'],
    ID: 'Australia/Brisbane',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Australian Eastern Standard Time (Queensland)',
  },
  {
    OFFSET: 36000000,
    SUB_GROUP: ['Pacific/Saipan'],
    ID: 'Pacific/Guam',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Chamorro Standard Time',
  },
  {
    OFFSET: 36000000,
    SUB_GROUP: ['Pacific/Truk', 'Pacific/Yap'],
    ID: 'Pacific/Chuuk',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Chuuk Time',
  },
  {
    OFFSET: 36000000,
    SUB_GROUP: [
      'Australia/ACT',
      'Australia/Canberra',
      'Australia/Currie',
      'Australia/NSW',
    ],
    ID: 'Australia/Sydney',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Australian Eastern Standard Time (New South Wales)',
  },
  {
    OFFSET: 36000000,
    SUB_GROUP: ['Australia/Victoria', 'Australia/Tasmania', 'Australia/Hobart'],
    ID: 'Australia/Melbourne',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Australian Eastern Standard Time (Victoria)',
  },
  {
    OFFSET: 36000000,
    ID: 'Antarctica/DumontDUrville',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Dumont-dUrville Time',
  },
  {
    OFFSET: 36000000,
    ID: 'Antarctica/Macquarie',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Macquarie Island Standard Time',
  },
  {
    OFFSET: 36000000,
    ID: 'Asia/Ust-Nera',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Ust-Nera Time',
  },
  {
    OFFSET: 36000000,
    ID: 'Asia/Vladivostok',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Vladivostok Time',
  },
  {
    OFFSET: 36000000,
    ID: 'Pacific/Port_Moresby',
    GMT_TIME_STAMP: '+10:00',
    DISPLAY_NAME: 'Papua New Guinea Time',
  },
  {
    OFFSET: 37800000,
    ID: 'Australia/Lord_Howe',
    GMT_TIME_STAMP: '+10:30',
    DISPLAY_NAME: 'Lord Howe Standard Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Asia/Magadan',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Magadan Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Asia/Sakhalin',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Sakhalin Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Asia/Srednekolymsk',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Srednekolymsk Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Pacific/Bougainville',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Bougainville Standard Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Pacific/Efate',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Vanuatu Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Pacific/Guadalcanal',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Solomon Is. Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Pacific/Kosrae',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Kosrae Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Pacific/Norfolk',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Norfolk Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Pacific/Noumea',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'New Caledonia Time',
  },
  {
    OFFSET: 39600000,
    ID: 'Pacific/Pohnpei',
    GMT_TIME_STAMP: '+11:00',
    DISPLAY_NAME: 'Pohnpei Time',
  },
  {
    OFFSET: 43200000,
    SUB_GROUP: ['Pacific/Majuro'],
    ID: 'Pacific/Kwajalein',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Marshall Islands Time',
  },
  {
    OFFSET: 43200000,
    SUB_GROUP: ['Antarctica/McMurdo', 'Pacific/Auckland'],
    ID: 'Antarctica/South_Pole',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'New Zealand Standard Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Asia/Anadyr',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Anadyr Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Asia/Kamchatka',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Petropavlovsk-Kamchatski Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Pacific/Fiji',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Fiji Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Pacific/Funafuti',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Tuvalu Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Pacific/Nauru',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Nauru Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Pacific/Tarawa',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Gilbert Is. Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Pacific/Wake',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Wake Time',
  },
  {
    OFFSET: 43200000,
    ID: 'Pacific/Wallis',
    GMT_TIME_STAMP: '+12:00',
    DISPLAY_NAME: 'Wallis & Futuna Time',
  },
  {
    OFFSET: 45900000,
    ID: 'Pacific/Chatham',
    GMT_TIME_STAMP: '+12:45',
    DISPLAY_NAME: 'Chatham Standard Time',
  },
  {
    OFFSET: 46800000,
    ID: 'Pacific/Apia',
    GMT_TIME_STAMP: '+13:00',
    DISPLAY_NAME: 'West Samoa Standard Time',
  },
  {
    OFFSET: 46800000,
    ID: 'Pacific/Enderbury',
    GMT_TIME_STAMP: '+13:00',
    DISPLAY_NAME: 'Phoenix Is. Time',
  },
  {
    OFFSET: 46800000,
    ID: 'Pacific/Fakaofo',
    GMT_TIME_STAMP: '+13:00',
    DISPLAY_NAME: 'Tokelau Time',
  },
  {
    OFFSET: 46800000,
    ID: 'Pacific/Tongatapu',
    GMT_TIME_STAMP: '+13:00',
    DISPLAY_NAME: 'Tonga Time',
  },
  {
    OFFSET: 50400000,
    ID: 'Pacific/Kiritimati',
    GMT_TIME_STAMP: '+14:00',
    DISPLAY_NAME: 'Line Is. Time',
  },
];
